stages:
  - build


maven-build:
  image: maven:3.6.0-jdk-8-alpine
  stage: build
  script: "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install -B"
